sched: fix compilation issues when WALT is disabled
Below compilation issues are observed when WALT is disabled,
fix them by adding proper checks.

1.
kernel/sched/rt.c:1770:39: \
	error: use of undeclared identifier 'FULL_THROTTLE_BOOST'

2.
kernel/sched/fair.c:7032:21: \
	error: use of undeclared identifier 'FULL_THROTTLE_BOOST'

Change-Id: I57d75490ae98fec44e0b2561c9e67c86e9d3a6ad
Signed-off-by: Satya Durga Srinivasu Prabhala <satyap@codeaurora.org>
UtsavBalar1231: fix indentation
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
Signed-off-by: Carlos Ayrton Lopez Arroyo <15030201@itcelaya.edu.mx>

 Conflicts:
	kernel/sched/fair.c